# Projeto 7 - MLOps com IaC Para Automação do Deploy de Modelo de Machine Learning na Nuvem

# Use uma imagem oficial do Python com uma distribuição leve
FROM python:3.11-slim

# Mantenedor da imagem (opcional)
LABEL maintainer="DSA"

# Atualizar os pacotes do sistema e instalar dependências adicionais necessárias
RUN apt-get update && \
    apt-get install -y wget unzip curl openssh-client iputils-ping && \
    rm -rf /var/lib/apt/lists/*

# Definir a versão do Terraform (ajuste conforme necessário)
ENV TERRAFORM_VERSION=1.10.2

# Baixar e instalar Terraform
RUN wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip && \
    unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip && \
    mv terraform /usr/local/bin/ && \
    rm terraform_${TERRAFORM_VERSION}_linux_amd64.zip

# Criar a pasta /iac como um ponto de montagem para um volume
RUN mkdir /iac
VOLUME /iac

# Criar a pasta Downloads e instalar o AWS CLI
RUN mkdir Downloads && \
    cd Downloads && \
    curl "https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install && \
    rm -rf /Downloads

# Criar diretório para a aplicação
WORKDIR /app

# Copiar o arquivo requirements.txt para o contêiner
COPY requirements.txt /app/

# Instalar pacotes do Python usando o requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

WORKDIR /iac

# Definir o comando padrão para execução quando o container for iniciado
CMD ["/bin/bash"]
